name: Checks
on: [ push, pull_request ]
jobs:
  Build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.commits[0].message, '[ci-skip]')"
    steps:
      - uses: actions/checkout@v3
      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 17

      - uses: gradle/wrapper-validation-action@v1
      - name: Make Gradle Wrapper executable
        run: chmod +x ./gradlew

      - name: Build
        run: ./gradlew build
